clubs_list = ["Paris-Saint-Germain", "Lens", "Brest", "Nice", "Toulouse", "Le-Havre", "Lorient", "Monaco", "Strasbourg", "Marseille", "Lille", "Reims", "Lyon", "Montpellier", "Metz", "Rennes", 
              "Nantes", "Clermont-Foot", "Bochum", "Mainz-05", "FC-Heidenheim", "Darmstadt", "FC-Koln", "Borussia-Dortmund", "Vfb-Stuttgart", "Bayer-Leverkusen", "Bayern-Munich", "Augsburg", 
              "Freiburg", "Werder-Bremen", "Union-Berlin", "Eintracht-Frankfurt", "Wolfsburg", "Borussia-M-Gladbach", "Hoffenheim", "RB-Leipzig", "Manchester-City", "Manchester-United", 
              "Sheffield-United", "Arsenal", "Liverpool", "West-Ham", "Aston-Villa", "Newcastle", "Brentford", "Brighton", "Crystal-Palace", "Bournemouth", "Nottingham-Forest", "Fulham", "Burnley",
              "Tottenham", "Wolves", "Everton", "Luton", "Chelsea", "Villarreal", "Mallorca", "Real-Madrid", "Sevilla", "Athletic-Club", "Celta-Vigo", "Real-Betis", "Deportivo-Alaves", 
              "Barcelona", "Girona", "Osasuna", "Atletico-Madrid", "Getafe", "Cadiz", "Almeria", "Granada", "Rayo-Vallecano", "Valencia", "Real-Sociedad", "Las-Palmas", "Udinese", "Cagliari", 
              "Juventus", "Sassuolo", "Empoli", "Lecce", "Roma", "Verona", "Salernitana", "Genoa", "Fiorentina", "Napoli", "Bologna", "Atalanta", "Monza", "Lazio", "Torino", 
              "Frosinone", "Inter", "AC-Milan", "Union-St-Gilloise", "Anderlecht", "Eupen", "Westerlo", "RWD-Molenbeek", "Genk", "Sporting-Charleroi", "OH-Leuven", "Royal-Antwerp", "Cercle-Bruges",
              "St-Truiden", "Standard-Liege", "Gent", "Kortijk", "Club-Bruges", "KV-Mechelen", "FC-Volendam", "Vitesse", "PSV-Eindhoven", "FC-Utrecht", "Ajax", "Heracles", "SC-Heerenveen",
              "RKC-Waalwijk", "PEC-Zwolle", "Sparta-Rotterdam", "NEC-Nijmegen", "Excelsior", "AZ-Alkmaar", "Go-Ahead-Eagles", "Feyenoord", "Fortuna-Sittard", "Almere City", "FC-Twente",
              "Braga", "Famalicao", "Farense", "Casa-Pia-AC", "Gil-Vicente", "Portimonense", "Sporting-CP", "Vizela", "Arouca", "Estoril", "Rio-Ave", "Chaves", "Estrela-da-Amadora",
              "Vitoria-de-Guimaraes", "Moreirense", "FC-Porto", "Boavista", "Southampton", "Ipswich", "Bournemouth", "Leganes", "Espanyol", "Real-Valladolid", "Como", "Venezia", 
              "Parma-Calcio-1913", "Holstein-Kiel", "St-Pauli", "Auxerre", "Angers", "Saint-Etienne", "Willem-II", "FC-Groningen", "Santa-Clara", "AVS-Futebol-SAD", "Nacional",
              "FCV-Dender-EH", "Beerschot", "NAC-Breda", "BSC-Young-Boys", "Dinamo-Zagreb", "Sparta-Prague", "Salzburg", "Shakhtar-Donetsk", "Slovan-Bratislava",
              "FK-Crvena-Zvezda", "Celtic", "Sturm-Graz", "Benfica"]


clubs_ids = {"Paris-Saint-Germain": 304,
             "Strasbourg": 148,
             "Lille": 607,
             "Nantes": 302,
             "Rennes": 313,
             "Monaco": 248,
             "Reims": 950,
             "Metz": 314,
             "Brest": 2332,
             "Le-Havre": 217,
             "Lens": 309,
             "Nice": 613,
             "Clermont-Foot":941,
             "Lorient": 146,
             "Montpellier": 311,
             "Marseille": 249,
             "Toulouse": 246,
             "Lyon": 228,
             "Bayer-Leverkusen": 36,
             "Darmstadt": 1147,
             "Bayern-Munich": 37,
             "FC-Heidenheim": 4852,
             "Mainz-05": 219,
             "FC-Koln": 282,
             "Wolfsburg": 33,
             "Eintracht-Frankfurt": 45,
             "Bochum": 109,
             "Borussia-M-Gladbach": 134,
             "VfB Stuttgart": 41,
             "Augsburg": 1730,
             "RB-Leipzig": 7614,
             "Freiburg": 50,
             "Werder-Bremen": 42,
             "Union-Berlin": 796,
             "Borussia-Dortmund": 44,
             "Hoffenheim": 1211,
             "Manchester-City": 167, 
             "Manchester-United": 32, 
              "Sheffield-United": 163, 
              "Arsenal": 13, 
              "Liverpool": 26, 
              "West-Ham": 29, 
              "Aston-Villa": 24, 
              "Newcastle": 23, 
              "Brentford": 189, 
              "Brighton": 211, 
              "Crystal-Palace": 162, 
              "Bournemouth": 183, 
              "Nottingham-Forest": 174, 
              "Fulham": 170, 
              "Burnley": 184,
              "Tottenham": 30, 
              "Wolves": 161, 
              "Everton": 31, 
              "Luton": 95, 
              "Chelsea": 15, 
              "Villarreal": 839, 
              "Mallorca": 51, 
              "Real-Madrid": 52, 
              "Sevilla": 67, 
              "Athletic-Club": 53, 
              "Celta-Vigo": 62, 
              "Real-Betis": 54, 
              "Deportivo-Alaves": 60, 
              "Barcelona": 65, 
              "Girona": 2783, 
              "Osasuna": 131, 
              "Atletico-Madrid": 63, 
              "Getafe": 819, 
              "Cadiz": 1354, 
              "Almeria": 1799, 
              "Granada": 925, 
              "Rayo-Vallecano": 64, 
              "Valencia": 55, 
              "Real-Sociedad": 68, 
              "Las-Palmas": 838, 
              "Udinese": 86, 
              "Cagliari": 78, 
              "Juventus": 87, 
              "Sassuolo": 2889, 
              "Empoli": 272, 
              "Lecce": 79, 
              "Roma": 84, 
              "Verona": 76, 
              "Salernitana": 143, 
              "Genoa": 278, 
              "Fiorentina": 73, 
              "Napoli": 276, 
              "Bologna": 71, 
              "Atalanta": 300, 
              "Monza": 269, 
              "Lazio": 77, 
              "Torino": 72, 
              "Frosinone": 2732, 
              "Inter": 75, 
              "AC-Milan": 80,
              "Union-St-Gilloise": 2647, 
              "Anderlecht": 240, 
              "Eupen": 2166, 
              "Westerlo": 238, 
              "RWD-Molenbeek": 1281, 
              "Genk": 140, 
              "Sporting-Charleroi": 260, 
              "OH-Leuven": 1406, 
              "Royal-Antwerp": 752, 
              "Cercle-Bruges": 885,
              "St-Truiden": 239, 
              "Standard-Liege": 261, 
              "Gent": 231, 
              "Kortijk": 886, 
              "Club-Bruges": 124, 
              "KV-Mechelen": 237,
              "FC-Volendam": 762, 
              "Vitesse": 255, 
              "PSV-Eindhoven": 129, 
              "FC-Utrecht": 128, 
              "Ajax": 130, 
              "Heracles": 870, 
              "SC-Heerenveen": 287,
              "RKC-Waalwijk": 114, 
              "PEC-Zwolle": 868, 
              "Sparta-Rotterdam": 303, 
              "NEC-Nijmegen": 116, 
              "Excelsior": 867, 
              "AZ-Alkmaar": 243, 
              "Go-Ahead-Eagles": 874, 
              "Feyenoord": 256, 
              "Fortuna-Sittard": 242, 
              "Almere City": 1347, 
              "FC-Twente": 113,
              "Braga": 288, 
              "Famalicao": 935, 
              "Farense": 263, 
              "Casa-Pia-AC": 9509, 
              "Gil-Vicente": 290, 
              "Portimonense": 1463, 
              "Sporting-CP": 296, 
              "Vizela": 2899, 
              "Arouca": 5948, 
              "Estoril": 2188, 
              "Rio-Ave": 121, 
              "Chaves": 2008, 
              "Estrela-da-Amadora": 28635,
              "Vitoria-de-Guimaraes": 107, 
              "Moreirense": 108, 
              "FC-Porto": 297, 
              "Boavista": 122,
              "Southampton": 18,
              "Ipswich": 165,
              "Bournemouth": 183,
              "Leganes": 825,
              "Espanyol": 70,
              "Real-Valladolid": 58,
              "Como": 1290,
              "Venezia": 85,
              "Parma-Calcio-1913": 24341,
              "Holstein-Kiel": 1206,
              "St-Pauli": 283,
              "Auxerre": 308, 
              "Angers": 614,
              "Saint-Etienne": 145,
              "Willem-II": 115,
              "FC-Groningen": 758,
              "Santa-Clara": 251,
              "AVS-Futebol-SAD": 2343,
              "Nacional": 936,
              "FCV-Dender-EH": 881,
              "Beerschot": 23686,
              "NAC-Breda": 783,
              "BSC-Young-Boys": 587,
              "Dinamo-Zagreb": 684,
              "Sparta-Prague": 354,
              "Salzburg": 361,
              "Shakhtar-Donetsk": 1706,
              "Slovan-Bratislava": 698,
              "FK-Crvena-Zvezda": 579,
              "Celtic": 103,
              "Sturm-Graz": 390,
              "Benfica": 299}

